baseURL = "/"
title = "fabian clemenz"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "fabian clemenz"
  info = "fullstack developer, tech enthusiast and yedi"
  description = "fabian Cclemenz's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "images/favicon.png"
  favicon_16 = "images/favicon.png"

  since = 2023

  colorScheme = "auto"
  hidecolorschemetoggle = false
  commit = "https://github.com/luizdepra/hugo-coder/tree/main"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/FabianClemenz/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/FabianClemenz/"
[[params.social]]
  name = "Stackoverflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 3
  url = "https://stackoverflow.com/users/14698152/fabianclemenz"
[[params.social]]
  name = "devsuit GmbH"
  icon = "fa fa-briefcase fa-2x"
  weight = 4
  url = "https://devsuit.de"

[[menu.main]]
  name = "about"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "blog"
  weight = 2
  url  = "posts/"